site_name: 帮助 | 开源之夏
site_dir: public
repo_url: https://summer-ospp.ac.cn/2023/help/en/
site_url: https://summer-ospp.ac.cn/2023/help/
repo_name: English Version

copyright: Copyright &copy; 2020 - 2023 开源软件供应链点亮计划 活动组委会

theme:
  name: material
  language: 'zh'
  features:
    - navigation.expand
  icon:
    repo: fontawesome/solid/link
  logo: assets/logo.svg
  favicon: assets/logo.svg

extra:
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:summer@iscas.ac.cn

extra_javascript:
    - 'js/tongji.js'

plugins:
  - git-revision-date
  - search:
      lang: ja

nav:
  - 热点问题: index.md
  - 活动角色: roles.md
  - 活动日程: timeline.md
  - 学生指南:
    - 常见问题: student.md
    - 项目申请建议: proj_apply.md
  - 社区指南: community.md
  - 社区名单: communities-list.md
  - 导师指南: mentor.md
  - 合作推广: cooperation.md
  - 联系我们: contactus.md
  - 感谢: acknowledgements.md
